#!/usr/bin/env python

import sys
import os

HELP = '''command line:  asdf_stl input.asdf output.stl
   input.asdf = input asdf file (mm units)
   output.stl = output binary stl file
'''
    
if len(sys.argv) != 3:
    print HELP
    sys.exit()

if not os.path.exists(sys.argv[1]):
    sys.stderr.write(
        "asdf_stl error: Can't find input file %s\n." % sys.argv[1]) 
    sys.exit(1)

# Load the ASDF file into memory.
from koko.c.asdf import ASDF
print "Loading ASDF file...   ",
sys.stdout.flush()
asdf = ASDF.load(sys.argv[1])

# Then render it to an image.
print "Done.\nTriangulating...   ",
sys.stdout.flush()
mesh = asdf.triangulate()

# Finally, save the image.
print "Done.\nSaving STL (%i triangles)...  " % mesh.tcount
sys.stdout.flush()
mesh.save_stl(sys.argv[2])

print "Done."
