#!/usr/bin/env python
import sys
import os

HELP = '''command line:  input.vol output.asdf ni nj nk density mm/voxel
   input.vol   = input .vol file
   output.stl  = output stl file
   ni, nj, nk  = dimensions along x, y, and z axes
   density     = value at which to threshold
   mm/voxel    = voxel side length in mm'''

if len(sys.argv) != 8 and len(sys.argv) != 9:
    print HELP
    sys.exit()

try:
    ni, nj, nk = map(int, sys.argv[3:6])
except ValueError:
    sys.stderr.write(
        'vol_stl error: ni, nj, nk must be integers.\n')
    sys.exit(1)

try:
    density    = float(sys.argv[6])
    mm_per_vox = float(sys.argv[7])
except ValueError:
    sys.stderr.write(
        'vol_stl error: density and mm/voxel must be floating-point values\n.')
    sys.exit(1)

from koko.c.asdf import ASDF

try:
    size = os.path.getsize(sys.argv[1])
except os.error:
    sys.stderr.write(
        "vol_stl error: Can't find input file %s\n." % sys.argv[1]) 
    sys.exit(1)
else:
    if size != ni*nj*nk*4:
        sys.stderr.write(
            "vol_stl error: File size doesn't match provided dimensions.\n")
        sys.exit(1)

print "Building .asdf...",
sys.stdout.flush()
asdf = ASDF.from_vol(sys.argv[1], ni, nj, nk, density,
                     mm_per_vox, decimate=False)

print "Done.\nTriangulating... ",
sys.stdout.flush()

mesh = asdf.triangulate()
print "Done.\nSaving .stl file...",
sys.stdout.flush()
mesh.save_stl(sys.argv[2])

print "Done."